# Data-driven Team Selection in Youth Basketball {#Mini-Moneyball}

#### Keywords{-}

Youth sports, sports analytics

## The Struggle for League Coordinators  
Youth sports offer a unique opportunity for young athletes to learn focus, dedication, and sportsmanship. These lessons are best taught through a well-balanced season, where players can experience both the reward of victory and the character-building that comes with defeat. It is often difficult to build balanced teams within a league, though, and one team may finish undefeated while another loses every single game. This imbalance may seem like a small issue or one that is overly obsessed with "fairness", but even an advocate for free competition can't ignore the consequences. An ESPN survey in 2013 revealed that the top reason players quit youth sports is because they do not have fun.^[Kelley, Bruce and Carl Carchia. "Hidden Demographics of Youth Sports". *ESPN Magazine*. Published 11 July 2013. http://www.espn.com/espn/story/_/id/9469252/hidden-demographics-youth-sports-espn-magazine] With even competition being an integral part of enjoyment, the issue of team balance in youth sports leagues is absolutely critical to retention.  
  
Unfortunately, volunteer coordinators for recreational leagues are simply not equipped for this challenge. They have limited player information, no tools, and short time frames to create teams. This project aims to better equip them by bringing the sports analytics revolution from the professional arena to youth leagues. The player assessment and team selection algorithms developed here will be game-changers in helping league coordinators create balanced seasons with competitive games. Ultimately, this will result in more lifelong athletes.  
  

## Sports Analytics Tailored for Youth
This project will take on two primary challenges: player evaluation and team composition.  

#### Player Evaluation - a data-driven "skill score"{-}  
First, the analysis will determine which statistics best capture a young basketball player's skill level. Traditional metrics such as *height* and *lay-ups made in 1 minute* will be weighed against less obvious factors such as *number of siblings in the league* and *birth month*. Player descriptions and performance data will initially be taken from previous seasons of local youth basketball programs, but the addition of family surveys for supplemental data will truly set this project apart. Particularly for sensitive information (with privacy concerns), obscure information (where record keeping may be incomplete), and "soft" metrics (such as *motivation for playing*), these surveys will offer more well-rounded information than has been used in the past.  
  
With information about so many aspects of a player's identity, the project will explore the relationships between all of these variables and uncover non-intuitive critical metrics. A small set of evaluation criteria will then be put forward as the most impactful, and some method of combining those metrics will be proposed to create a single-value "skill score".  
  
#### Team Composition{-}  
With the "skill-score" metric defined, the project will then develop a model to associate a team's overall composition with its performance. This will answer the classic question: can one all-star create a winning season for his team? Or are team dynamics and complementary skills the key to success? Win/loss records will be modeled as a function of mean skill, range of skill, maximum skill, and other characterizations in order to determine which is the defining statistic.  
  
Finally, the project will create a hypothetical player population and evaluate common team selection techniques and determine which results in the best team composition throughout the league. A "random selection" model will be used as a baseline, to ensure that any proposed selection process results in some increase to equality. Beyond that, a draft model (with turns taken around a table) will be compared to various algorithmic methods to determine which results in a set of fully competitive teams.  
  
## Athletes for Life  
The two studies described above will combine to offer a revolutionary total solution to league coordinators: advice on what player metrics to capture and how to translate those measurements into team assignments. There will be limitations, of course, and league coordinators may only be able to implement a small part of the suggestions given here. Even in a limited form, though, this project will improve the balance of teams so that young players can be introduced to basketball in an engaging and enjoyable way. The season's losses will be balanced by the satisfaction that comes with competition, and athletes will learn dedication and focus. Most importantly, they will be more likely to return to the court in subsequent seasons.
